# Generated by Django 4.0.2 on 2022-02-02 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товарар')),
                ('type', models.CharField(max_length=200, verbose_name='Тип товара')),
                ('date_delivery', models.DateTimeField(verbose_name='Дата доставки')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.CharField(max_length=200, verbose_name='Адрес доставки')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.delivey', verbose_name='Заказ')),
            ],
        ),
    ]
