# Generated by Django 4.0.2 on 2022-02-02 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivey',
            new_name='Delivery',
        ),
    ]
